dfarchon/darkforest-mud

package.json
What the title says, i think we should all be aligned on Node >= 20, Node 22 will be the new long term support (LTS) version from next month october, also Node 18 has been in maintenance since last year.
https://nodejs.org/en/about/previous-releases
=> Chore: enforce node >= 20 <21

package.json, pnpm-lock.yaml
What the title says ☝️  
1. Since these are only used under dev and we don't ship them the should also be added to `devDependencies`.
2. We introduced `^` for `@latticexyz/explorer`, may lead to others installing newer versions these dependencies should always have same version.
The reactive-native peer deps issue, is something that needs to be fixed in the `@metamask/sdk` package outside of our scope, since we will never use this they should have added it as an optional peer dep 👇
=> Chore: move latticexyz under devdeps

packages/client/docs/TypeScript.md, packages/client/package.json, packages/client/src/Frontend/Components/RemoteModal.tsx, packages/client/src/hooks/useBalance.ts, packages/client/src/mud/createSystemCalls.ts, packages/client/src/wallet/WalletButton.tsx, packages/client/src/wallet/WalletPane.tsx, packages/client/tsconfig.json
What the title says ☝️ , i'm also leaning into just not inheriting from the `@latticexyz/common/tsconfig.base.json` since it does not do us any good here 🤷, also in case they decided todo changes in their config in the future that may lead to bugs that are a bit hard to find (however these changes will be fixed in a separate PRs)
- [`noEmit = true`](https://www.typescriptlang.org/tsconfig#noEmit); disables generating js files from ts files under compilation.
- [`noErrorTruncation = true`](https://www.typescriptlang.org/tsconfig#noErrorTruncation); Disable truncating types in error messages.
- [`resolveJsonModule = true`](https://www.typescriptlang.org/tsconfig#resolveJsonModule); Enabled importing JSON files.
- [`forceConsistentCasingInFileNames = …
=> Tune TSConfig and add some docs

packages/client/docs/TypeScript.md, packages/client/package.json, packages/client/tsconfig.json
We don't extend the root tsconfig from the client, and remove dependency on the latticexyz base config which we are already extending and overriding most of them anyways.
Things work as before
Tested that TS compiler did not emit any errors neither in the Editor nor from the Terminal
This is a follow up on #14
=> Client: TSConfig dont extend latticexyz config

packages/client/docs/TypeScript.md, packages/client/src/Backend/Miner/MinerManager.ts, packages/client/src/Frontend/Components/LoadingSpinner.tsx, packages/client/src/Frontend/Components/Text.tsx, packages/client/src/Shared/renderer/Entities/PlanetRenderManager.ts, packages/client/src/Shared/renderer/Memes.ts, packages/client/src/Shared/renderer/Overlay2DRenderer.ts, packages/client/src/Shared/renderer/Programs/NoiseProgram.ts, packages/client/src/Shared/renderer/TextureManager.ts, packages/client/src/Shared/renderer/UIRenderer.ts, packages/client/src/Shared/serde/artifact.ts, packages/client/src/mud/createSystemCalls.ts, packages/client/tsconfig.json
This is a follow up on #14 , and enables the following compiler options:
1.  [`noUnusedLocals = true`](https://www.typescriptlang.org/tsconfig#noUnusedLocals); Reports on unused local variables.
2. [`noUnusedParameters = true`](https://www.typescriptlang.org/tsconfig#noUnusedParameters); Reports on unused parameters in functions.
This helps us reason over the TS code better,  and see what local variables and function parameters that are in use or not, it also helps us see and remove unused code and keeping our codebase tidy 👌 
NOTE: If one want's to keep some code that is currently not in use, however not remove it from the codebase in some file one can always use the `@ts-ignore` directive with a comment, that will turn off the error reporting on it.
=> TSConfig: Enable no unused variables and function parameters compiler options

packages/client/.eslintrc, packages/client/src/App.tsx, packages/client/src/Frontend/Components/AncientLabel.tsx, packages/client/src/Frontend/Components/ArtifactImage.tsx, packages/client/src/Frontend/Components/DisplayGasPrices.tsx, packages/client/src/Frontend/Components/GameLandingPageComponents.tsx, packages/client/src/Frontend/Components/Icons.tsx, packages/client/src/Frontend/Components/Labels/ArtifactLabels.tsx, packages/client/src/Frontend/Components/Labels/BiomeLabels.tsx, packages/client/src/Frontend/Components/LoadingSpinner.tsx, packages/client/src/Frontend/Components/RemoteModal.tsx, packages/client/src/Frontend/Components/TimeUntil.tsx, packages/client/src/Frontend/Pages/LandingPage.tsx, packages/client/src/Frontend/Styles/Mixins.tsx, packages/client/src/Frontend/Views/CadetWormhole.tsx, packages/client/src/PlanetTest/CreateMoveFormTest.tsx, packages/client/src/PlanetTest/PlanetTestPage.tsx, packages/client/src/PlanetTest/PlayPauseButton.tsx, packages/client/src/wallet/Components/SpawnPlayerPane.tsx, packages/client/src/wallet/ExternalWalletProvider.tsx, packages/client/src/wallet/WalletButton.tsx, packages/client/src/wallet/WalletPane.tsx
what the title says ☝🏽 , from react TS >= 4.1 and React >= 17 with the new jsx transfrm, one does not need to import the React from JSX or TSX files, unless React is directly used.
- [Introducing the new JSX Transform - ESlint](https://ru.legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.htm)
- [TS 4.1 - React 17 JSX Factories](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)
- [TS Doc - Handbook](https://www.typescriptlang.org/docs/handbook/jsx.html)
=> fix: react no longer required to be imported from tsx or jsx files

packages/client/package.json, packages/client/src/Backend/Miner/MinerManager.ts, packages/client/src/Shared/whitelist/index.ts, pnpm-lock.yaml
No need to use lodash for these purposes:
1. The lodash `_.replace` was replaced with `String.replaceAll()` that is widely supported these days
2. The lodash `_.range` was replaced with a custom range function 
3. The lodash `_.chunk` was replaced with custom code that does the same
```ts
const range = (size: number, step = 1) =>
[...new Array(size)].map((_, index) => index - step);
```
```ts
Array.from(hexValue.matchAll(/(.{1,6})/g))
.map(([match]) => match)
.join('-')
.toUpperCase();
```
=> Client: remove dependency on lodash

packages/client/package.json, pnpm-lock.yaml
Addresses security issues with vite, and bumps to major versions of vite 👍
=> chore: bump vite to v5.x and vite plugin to 4.x

.husky/commit-msg, .husky/pre-commit, package.json, packages/client/package.json, pnpm-lock.yaml
1. Bumps husky to v9
2. Eslint fix
3. The format command was wrong was using glob pattern `{packages}/**/*` when it should have been `packages/**/*` , if we want to match multiple directories e.g. packages and apps we would hav needed glob `{app,packages}/**/*`.
1. With husky v9, we only need to run `husky` without `install`
2. We also no longer need to use `npx` from commit-msg and pre-commit since it fixes the path.
Adds the script command `lint-fix:eslint` e.g.: 👇 
Will try to fix all eslint errors and warnings that are possible to autofix 👍 .
Can also be run from root via `pnpm lint-fix` or `pnpm --filter client lint-fix:eslint`
=> chore: bump husky to v9 and fix eslint + format

packages/client/src/Frontend/Components/BrowserIssues.tsx, packages/client/src/Frontend/Pages/GameLandingPage.tsx, packages/client/src/_types/global/GlobalTypes.ts
What's done here 
Ran `pnpm lint:eslint --fix` first from the `packages/client` directory 👇 :
Which autofixed what it could.
Ran `pnpm lint:typecheck` from the `packages/client` directory 👇 :
Found 22 errors ☝️ , and fixed them manually.
=> fix: eslint and typescript issues

.github/CODEOWNERS
This reverts the change in #38, the code owners should be the dev group not admin.
Just to be clear here:
1. That a group is set in the Codeowners file does not mean they own the repo or anything. This jus means who should get a PR assignment notification.
2. The df-admin group is now only @cherryblue1024 and @ClaudeZsb , they have super admin rights that can bypass anything and that was what we agreed on.
From the docs [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners):
>Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more …
=> fix: codeowners should be dev not admin

.eslintrc.cjs, packages/client/src/Backend/GameLogic/InitialGameStateDownloader.tsx, packages/client/src/PlanetTest/ProofVerificationForm.tsx, packages/client/src/Shared/network/TxExecutor.ts
what the title says. ☝️ , as the eslint rule says [here](https://typescript-eslint.io/rules/no-explicit-any/):
>The any type in TypeScript is a dangerous "escape hatch" from the type system. Using any disables many type checking rules and is generally best used only as a last resort or when prototyping code. This rule reports on explicit uses of the any keyword as a type annotation.
Also on why TS no implicit any does not enforce this.
>TypeScript's --noImplicitAny compiler option prevents an implied any, but doesn't prevent any from being explicitly used the way this rule does.
This rules enforces to take choices and read the code, and say something is of type X and not Y which also reduces debug time when things go wrong…
=> chore: enforce no explicit any

.eslintrc.cjs, packages/client/src/Backend/GameLogic/ContractsAPI.ts, packages/client/src/Backend/GameLogic/GameManager.ts, packages/client/src/Backend/GameLogic/GameObjects.ts, packages/client/src/Backend/GameLogic/GameUIManager.ts, packages/client/src/Backend/GameLogic/TutorialManager.ts, packages/client/src/Backend/Network/UtilityServerAPI.ts, packages/client/src/Backend/Storage/PersistentChunkStore.ts, packages/client/src/Backend/Storage/ReaderDataStore.ts, packages/client/src/Frontend/Game/ControllableCanvas.tsx, packages/client/src/Frontend/Game/ModalManager.ts, packages/client/src/Frontend/Game/NotificationManager.tsx, packages/client/src/Frontend/Game/Popups.ts, packages/client/src/Frontend/Game/Viewport.ts, packages/client/src/Frontend/Pages/GameLandingPage.tsx, packages/client/src/Frontend/Pages/GifMaker.tsx, packages/client/src/Frontend/Renderers/Artifacts/ArtifactRenderer.ts, packages/client/src/Frontend/Renderers/GifRenderer.ts, packages/client/src/Frontend/Renderers/LandingPageCanvas.tsx, packages/client/src/Frontend/Utils/EmitterUtils.ts, packages/client/src/Frontend/Utils/KeyEmitters.ts, packages/client/src/PlanetTest/PlanetUpgradeFormBranchTest.tsx, packages/client/src/PlanetTest/PlayerForm.tsx, packages/client/src/PlanetTest/ProofVerificationForm.tsx, packages/client/src/PlanetTest/RevealPlanetForm.tsx, packages/client/src/Shared/network/ContractCaller.ts, packages/client/src/Shared/network/EthConnection.ts, packages/client/src/Shared/network/ThrottledConcurrentQueue.ts, packages/client/src/Shared/network/TxExecutor.ts
what the title says ☝️ , we should always prefer readability over simplicity and eventual bugs when compiling JS that are difficult to discover in running code…
As it says [here](https://eslint.org/docs/latest/rules/curly) 
> JavaScript allows the omission of curly braces when a block contains only one statement. However, it is considered by many to be best practice to never omit curly braces around blocks, even when they are optional, because it can lead to bugs and reduces code clarity. So the following:
[Rule details](https://eslint.org/docs/latest/rules/curly#rule-details)
> This rule is aimed at preventing bugs and increasing code clarity by ensuring that block statements are wrapped in curly braces. It will warn when it encounters blocks that omit curly braces.
=> fix: eslint enforce curly

packages/client/src/Backend/GameLogic/PluginManager.tsx
What the title says ☝️ , since we now use vite we need to use the `@vite-ignore` comment for dynamic imports instead of the old webpack ignore comment.
Addresses this warning 👇
=> fix: vite ignore warning

.gitignore
I want to ignore the [node version manager](https://github.com/nvm-sh/nvm) file`.nvmrc` file to make it easier to switch between the current LTS version 22 of node, and the version 20 of node that i'm using for this project.
=> chore: ignore .nvmrc file

packages/client/src/Backend/GameLogic/InitialGameStateDownloader.tsx, packages/client/src/Frontend/Game/NotificationManager.tsx, packages/client/src/Frontend/Pages/GameLandingPage.tsx, packages/client/src/Frontend/Panes/ArtifactDetailsPane.tsx, packages/client/src/Frontend/Panes/Lobbies/CaptureZonesPane.tsx, packages/client/src/Frontend/Panes/Lobbies/ConfigurationPane.tsx, packages/client/src/Frontend/Panes/Lobbies/PlanetPane.tsx, packages/client/src/Frontend/Panes/Lobbies/RewardsPane.tsx, packages/client/src/Frontend/Panes/Lobbies/SpaceJunkPane.tsx, packages/client/src/Frontend/Panes/TransactionLogPane.tsx, packages/client/src/Frontend/Views/DarkForestTips.tsx, packages/client/src/Frontend/Views/Notifications.tsx, packages/client/src/Shared/utils/comparison/index.ts, packages/client/src/Shared/utils/comparison/is-empty.ts, packages/client/src/Shared/utils/list/chunk.ts, packages/client/src/Shared/utils/list/index.ts, packages/client/src/Shared/utils/list/reversed.ts, packages/client/src/Shared/utils/list/shuffle.ts, packages/client/src/Shared/utils/number/index.ts, packages/client/src/Shared/utils/number/range.ts, packages/client/src/Shared/utils/string/index.ts, packages/client/src/Shared/utils/string/start-case.ts
Follow up on #139, seems that there was more functionality used from `lodash` than what i saw when i forked from main.
This should fix the last bits and pieces.
I have tested that most of the utility replacements functions work as expected will add tests for those functions in a separate PR, and start introducing test suites for our JS codebase gradually (we can't keep going on without tests like we have done for some time now).
=> chore: add functionality to replace lodash-es

packages/client/package.json, packages/client/src/Backend/GameLogic/PlanetUtils.ts, packages/client/src/Shared/serde/location.test.ts, packages/client/src/Shared/serde/location.ts, pnpm-lock.yaml
What the title says ☝️:
1. Simplifies the serde locations utils 
2. Adds tests for the aforementioned utils
The test suite covers all cases for from/to pasing of locationId 👇 
This speeds up and reduces memory footprint used by avoiding string concatenation, when we are using the utilities to parse location Ids to and from different formats,.
Will add Github workflow for client tests as a separate PR.
This was done as part of the PR #156, however adding this a separate PR since it makes sense to have it as a standalone PR.
=> Simplify serde locations

packages/client/src/Backend/GameLogic/PluginManager.tsx
It used to be `/* @vite-ignore: true */` however now they have changed it to `/* @vite-ignore */` only (makes sens, if it's there 🤷 )
=> Plugin manager: fix vite-ignore

packages/client/embedded_plugins/MemoryMonitor.js, packages/client/src/Backend/GameLogic/GameManager.ts, packages/client/src/Backend/Plugins/EmbeddedPluginLoader.ts
Instead of printing "memory info" via console.log to dev console every 200ms, which makes it difficult to:
1. Use the dev console for anything anything besides reading the memory info.
2. Use the dev console to read other debug statements.
3. Work interactively with the dev console.
We now have a plugin that we can run in game to see the memory usage like this 👇
=> Memory Monitor Plugin

.gitignore, packages/client/package.json, packages/client/vite.config.ts, pnpm-lock.yaml
What the title says ☝️ , vite version 6 has been out for some while now, it also addresses some critical severity issues listed [here](https://github.com/dfarchon/darkforest-mud/security/dependabot?q=is%3Aopen+sort%3Aseverity+severity%3Acritical)
Tested that vite hot module reload (HMR) still works  ✅
=> Bump Vite to v6
